# PyTorch入门

In [1]:
import torch
x = torch.tensor([1,2])
x

tensor([1, 2])

In [2]:
x.new_ones(5,3)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [3]:
x.t

<function Tensor.t>

In [4]:
x = torch.tensor([1,2])
x = x.new_ones(5, 3)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x,dtype = torch.float)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[ 0.1168, -1.7098, -0.1888],
        [-0.8839, -0.9513, -1.9180],
        [ 0.2291,  0.9863,  1.7211],
        [ 0.8906, -0.0884,  0.6102],
        [-1.4204,  0.0613, -1.1187]])


In [5]:
x = torch.randn(3, requires_grad=True)
x
y = x * 2
print(y)
y.data


tensor([-0.2105, -1.2662, -1.6553])

In [6]:
y.data.norm()

tensor(2.0947)

In [7]:
import numpy as np
import torch

In [8]:
np.array([1,2,3]) # ndarrays

array([1, 2, 3])

In [9]:
torch.tensor([1,2,3]) # tensor

tensor([1, 2, 3])

In [10]:
# tensor相关的函数 & 运算

In [11]:
torch.empty(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.randn(5,3) # 随机初始化的矩阵 包括以后一些网络模型 想去确认一些维度 模型结构 可能需要一些数据进行投喂

tensor([[ 0.0819, -1.4773, -0.3198],
        [ 2.2769,  0.5956,  1.2860],
        [-0.0383, -0.7507,  0.3220],
        [ 1.7705,  2.0655,  0.2639],
        [ 0.9812,  0.5314,  0.1384]])

In [13]:
torch.zeros(5,3,dtype = torch.long) # x → y 训练这样一个映射 神经网络 y truth_label one-hot表示
# dtype 表示 数据格式

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [14]:
# 基于已存在的tensor去操作
x = torch.tensor([1,2,3])
x.new_ones(5,3)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.randn_like(x,dtype = torch.float)

tensor([-0.2341,  0.0432, -0.5351])

In [16]:
# 查看维度 层到另外一层 矩阵相乘
np.array([1,2,3]).shape
torch.tensor([1,2,3]).size()

torch.Size([3])

In [17]:
torch.randn(5,3).size()[1]

3

In [18]:
# 运算 加减乘除
x = torch.randn(5,3)
x
y = torch.randn(5,3)
y
print(x+y)

tensor([[ 2.7642, -1.6939,  1.1459],
        [-0.4519, -0.3483, -0.5025],
        [-0.1733,  0.6000, -1.5553],
        [-1.2253,  0.1161, -2.4036],
        [-2.6962,  1.1600,  1.8629]])


In [19]:
z = torch.empty(5,3)
torch.add(x,y,out = z)
print(z)

tensor([[ 2.7642, -1.6939,  1.1459],
        [-0.4519, -0.3483, -0.5025],
        [-0.1733,  0.6000, -1.5553],
        [-1.2253,  0.1161, -2.4036],
        [-2.6962,  1.1600,  1.8629]])


In [20]:
# adds x to y inplace  '_'
y.add_(x)

tensor([[ 2.7642, -1.6939,  1.1459],
        [-0.4519, -0.3483, -0.5025],
        [-0.1733,  0.6000, -1.5553],
        [-1.2253,  0.1161, -2.4036],
        [-2.6962,  1.1600,  1.8629]])

In [21]:
# 操作 取 更改维度 取数值
np.array([[1,2,3],[4,5,6]])[:,2] # :表示不指定行 默认是所有

array([3, 6])

In [22]:
y.view(-1,5)

tensor([[ 2.7642, -1.6939,  1.1459, -0.4519, -0.3483],
        [-0.5025, -0.1733,  0.6000, -1.5553, -1.2253],
        [ 0.1161, -2.4036, -2.6962,  1.1600,  1.8629]])

In [23]:
y[3,0].item() # 非常常用 loss 反向传导 打一下日志记录/画图 loss是否在减少 print(value)

-1.2252964973449707

In [24]:
# https://www.jianshu.com/p/7dbfc7076e5a

In [25]:
torch.zeros_like(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])