# PyTorch自动微分

In [73]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [74]:
# 训练 train backward 验证/评估evaluate 
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [75]:
y.grad_fn

In [76]:
z = y*y*3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [77]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward1>)

In [80]:
# out = sum(3(x+2)^2)/4   3/4 * (x+2)^2  3/2*(x+2)
out.backward()

In [81]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])